//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condiciones.ServicioClausulaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaCondicionesDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ConsultaCondicionesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO ConsultaPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ConsultaCondicionesUpgradeDTO[] UpgradesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anual {
            get {
                return this.AnualField;
            }
            set {
                if ((this.AnualField.Equals(value) != true)) {
                    this.AnualField = value;
                    this.RaisePropertyChanged("Anual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((this.CodigoPaisField.Equals(value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTarifa {
            get {
                return this.CodigoTarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTarifaField, value) != true)) {
                    this.CodigoTarifaField = value;
                    this.RaisePropertyChanged("CodigoTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO ConsultaPadre {
            get {
                return this.ConsultaPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultaPadreField, value) != true)) {
                    this.ConsultaPadreField = value;
                    this.RaisePropertyChanged("ConsultaPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoModalidad {
            get {
                return this.IdTipoModalidadField;
            }
            set {
                if ((this.IdTipoModalidadField.Equals(value) != true)) {
                    this.IdTipoModalidadField = value;
                    this.RaisePropertyChanged("IdTipoModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoPlan {
            get {
                return this.IdTipoPlanField;
            }
            set {
                if ((this.IdTipoPlanField.Equals(value) != true)) {
                    this.IdTipoPlanField = value;
                    this.RaisePropertyChanged("IdTipoPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ConsultaCondicionesUpgradeDTO[] Upgrades {
            get {
                return this.UpgradesField;
            }
            set {
                if ((object.ReferenceEquals(this.UpgradesField, value) != true)) {
                    this.UpgradesField = value;
                    this.RaisePropertyChanged("Upgrades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaCondicionesUpgradeDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ConsultaCondicionesUpgradeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUpgradeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTarifa {
            get {
                return this.CodigoTarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTarifaField, value) != true)) {
                    this.CodigoTarifaField = value;
                    this.RaisePropertyChanged("CodigoTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUpgrade {
            get {
                return this.CodigoUpgradeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUpgradeField, value) != true)) {
                    this.CodigoUpgradeField = value;
                    this.RaisePropertyChanged("CodigoUpgrade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GruposClausulaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class GruposClausulaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.GrupoClausulaDTO[] GruposField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.GrupoClausulaDTO[] Grupos {
            get {
                return this.GruposField;
            }
            set {
                if ((object.ReferenceEquals(this.GruposField, value) != true)) {
                    this.GruposField = value;
                    this.RaisePropertyChanged("Grupos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoClausulaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class GrupoClausulaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ContenidoClausulaDTO[] ClausulasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasConsecutivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.DocumentoDTO[] DocumentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLocacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.TarifaDTO[] TarifasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoGrupoClausulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anual {
            get {
                return this.AnualField;
            }
            set {
                if ((this.AnualField.Equals(value) != true)) {
                    this.AnualField = value;
                    this.RaisePropertyChanged("Anual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ContenidoClausulaDTO[] Clausulas {
            get {
                return this.ClausulasField;
            }
            set {
                if ((object.ReferenceEquals(this.ClausulasField, value) != true)) {
                    this.ClausulasField = value;
                    this.RaisePropertyChanged("Clausulas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasConsecutivos {
            get {
                return this.DiasConsecutivosField;
            }
            set {
                if ((this.DiasConsecutivosField.Equals(value) != true)) {
                    this.DiasConsecutivosField = value;
                    this.RaisePropertyChanged("DiasConsecutivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.DocumentoDTO[] Documentos {
            get {
                return this.DocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentosField, value) != true)) {
                    this.DocumentosField = value;
                    this.RaisePropertyChanged("Documentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLocacion {
            get {
                return this.IdLocacionField;
            }
            set {
                if ((this.IdLocacionField.Equals(value) != true)) {
                    this.IdLocacionField = value;
                    this.RaisePropertyChanged("IdLocacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.TarifaDTO[] Tarifas {
            get {
                return this.TarifasField;
            }
            set {
                if ((object.ReferenceEquals(this.TarifasField, value) != true)) {
                    this.TarifasField = value;
                    this.RaisePropertyChanged("Tarifas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoGrupoClausula {
            get {
                return this.TipoGrupoClausulaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoGrupoClausulaField, value) != true)) {
                    this.TipoGrupoClausulaField = value;
                    this.RaisePropertyChanged("TipoGrupoClausula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContenidoClausulaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ContenidoClausulaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ClausulaDTO ClausulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoImpresionClausulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.CondicionEvaluacion[] CondicionesEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EvaluableEnAsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ContenidoClausulaDTO[] PadresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ContenidoClausulaRangoDTO[] RangosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCoberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleEnAsistenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ClausulaDTO Clausula {
            get {
                return this.ClausulaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClausulaField, value) != true)) {
                    this.ClausulaField = value;
                    this.RaisePropertyChanged("Clausula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoImpresionClausula {
            get {
                return this.CodigoTipoImpresionClausulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoImpresionClausulaField, value) != true)) {
                    this.CodigoTipoImpresionClausulaField = value;
                    this.RaisePropertyChanged("CodigoTipoImpresionClausula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.CondicionEvaluacion[] CondicionesEvaluacion {
            get {
                return this.CondicionesEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionesEvaluacionField, value) != true)) {
                    this.CondicionesEvaluacionField = value;
                    this.RaisePropertyChanged("CondicionesEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EvaluableEnAsistencia {
            get {
                return this.EvaluableEnAsistenciaField;
            }
            set {
                if ((this.EvaluableEnAsistenciaField.Equals(value) != true)) {
                    this.EvaluableEnAsistenciaField = value;
                    this.RaisePropertyChanged("EvaluableEnAsistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ContenidoClausulaDTO[] Padres {
            get {
                return this.PadresField;
            }
            set {
                if ((object.ReferenceEquals(this.PadresField, value) != true)) {
                    this.PadresField = value;
                    this.RaisePropertyChanged("Padres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ContenidoClausulaRangoDTO[] Rangos {
            get {
                return this.RangosField;
            }
            set {
                if ((object.ReferenceEquals(this.RangosField, value) != true)) {
                    this.RangosField = value;
                    this.RaisePropertyChanged("Rangos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCobertura {
            get {
                return this.TipoCoberturaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCoberturaField, value) != true)) {
                    this.TipoCoberturaField = value;
                    this.RaisePropertyChanged("TipoCobertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisibleEnAsistencia {
            get {
                return this.VisibleEnAsistenciaField;
            }
            set {
                if ((this.VisibleEnAsistenciaField.Equals(value) != true)) {
                    this.VisibleEnAsistenciaField = value;
                    this.RaisePropertyChanged("VisibleEnAsistencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class DocumentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoDimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoTipoContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoValidacion {
            get {
                return this.CodigoValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoValidacionField, value) != true)) {
                    this.CodigoValidacionField = value;
                    this.RaisePropertyChanged("CodigoValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentoDimension {
            get {
                return this.DocumentoDimensionField;
            }
            set {
                if ((this.DocumentoDimensionField.Equals(value) != true)) {
                    this.DocumentoDimensionField = value;
                    this.RaisePropertyChanged("DocumentoDimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoTipoContenido {
            get {
                return this.DocumentoTipoContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoTipoContenidoField, value) != true)) {
                    this.DocumentoTipoContenidoField = value;
                    this.RaisePropertyChanged("DocumentoTipoContenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((this.IdDocumentoField.Equals(value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarifaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class TarifaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SufijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((this.CodigoPaisField.Equals(value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTarifa {
            get {
                return this.CodigoTarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTarifaField, value) != true)) {
                    this.CodigoTarifaField = value;
                    this.RaisePropertyChanged("CodigoTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo {
            get {
                return this.SufijoField;
            }
            set {
                if ((object.ReferenceEquals(this.SufijoField, value) != true)) {
                    this.SufijoField = value;
                    this.RaisePropertyChanged("Sufijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClausulaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ClausulaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.ClausulaIdiomaDTO[] ClausulaIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoClausulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTipoClausulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.ClausulaIdiomaDTO[] ClausulaIdioma {
            get {
                return this.ClausulaIdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.ClausulaIdiomaField, value) != true)) {
                    this.ClausulaIdiomaField = value;
                    this.RaisePropertyChanged("ClausulaIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoClausula {
            get {
                return this.CodigoTipoClausulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoClausulaField, value) != true)) {
                    this.CodigoTipoClausulaField = value;
                    this.RaisePropertyChanged("CodigoTipoClausula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoClausula {
            get {
                return this.NombreTipoClausulaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTipoClausulaField, value) != true)) {
                    this.NombreTipoClausulaField = value;
                    this.RaisePropertyChanged("NombreTipoClausula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CondicionEvaluacion", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class CondicionEvaluacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDato {
            get {
                return this.TipoDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDatoField, value) != true)) {
                    this.TipoDatoField = value;
                    this.RaisePropertyChanged("TipoDato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContenidoClausulaRangoDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ContenidoClausulaRangoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadMaximaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadMinimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdValidezTerritorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdValidezTerritorialClausulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Condiciones.ServicioClausulaWCF.LeyendaDTO[] LeyendasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPlanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadMaxima {
            get {
                return this.EdadMaximaField;
            }
            set {
                if ((this.EdadMaximaField.Equals(value) != true)) {
                    this.EdadMaximaField = value;
                    this.RaisePropertyChanged("EdadMaxima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EdadMinima {
            get {
                return this.EdadMinimaField;
            }
            set {
                if ((this.EdadMinimaField.Equals(value) != true)) {
                    this.EdadMinimaField = value;
                    this.RaisePropertyChanged("EdadMinima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValidezTerritorial {
            get {
                return this.IdValidezTerritorialField;
            }
            set {
                if ((this.IdValidezTerritorialField.Equals(value) != true)) {
                    this.IdValidezTerritorialField = value;
                    this.RaisePropertyChanged("IdValidezTerritorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdValidezTerritorialClausula {
            get {
                return this.IdValidezTerritorialClausulaField;
            }
            set {
                if ((this.IdValidezTerritorialClausulaField.Equals(value) != true)) {
                    this.IdValidezTerritorialClausulaField = value;
                    this.RaisePropertyChanged("IdValidezTerritorialClausula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Condiciones.ServicioClausulaWCF.LeyendaDTO[] Leyendas {
            get {
                return this.LeyendasField;
            }
            set {
                if ((object.ReferenceEquals(this.LeyendasField, value) != true)) {
                    this.LeyendasField = value;
                    this.RaisePropertyChanged("Leyendas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoModalidad {
            get {
                return this.TipoModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoModalidadField, value) != true)) {
                    this.TipoModalidadField = value;
                    this.RaisePropertyChanged("TipoModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPlan {
            get {
                return this.TipoPlanField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPlanField, value) != true)) {
                    this.TipoPlanField = value;
                    this.RaisePropertyChanged("TipoPlan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClausulaIdiomaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class ClausulaIdiomaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIdioma {
            get {
                return this.IdIdiomaField;
            }
            set {
                if ((this.IdIdiomaField.Equals(value) != true)) {
                    this.IdIdiomaField = value;
                    this.RaisePropertyChanged("IdIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeyendaDTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioConsultaClausulas")]
    [System.SerializableAttribute()]
    public partial class LeyendaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIdioma {
            get {
                return this.IdIdiomaField;
            }
            set {
                if ((this.IdIdiomaField.Equals(value) != true)) {
                    this.IdIdiomaField = value;
                    this.RaisePropertyChanged("IdIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioClausulaWCF.IServicioClausulas")]
    public interface IServicioClausulas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClausulas/ObtenerCondiciones", ReplyAction="http://tempuri.org/IServicioClausulas/ObtenerCondicionesResponse")]
        Condiciones.ServicioClausulaWCF.GruposClausulaDTO ObtenerCondiciones(Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO Consulta, string Usuario, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClausulas/ObtenerCondicionesXml", ReplyAction="http://tempuri.org/IServicioClausulas/ObtenerCondicionesXmlResponse")]
        string ObtenerCondicionesXml(string XmlConsulta, string Usuario, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClausulas/ConvertirConsulta", ReplyAction="http://tempuri.org/IServicioClausulas/ConvertirConsultaResponse")]
        string ConvertirConsulta(Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO Consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClausulas/ConvertirGrupos", ReplyAction="http://tempuri.org/IServicioClausulas/ConvertirGruposResponse")]
        string ConvertirGrupos(Condiciones.ServicioClausulaWCF.GruposClausulaDTO Grupos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServicioClausulasChannel : Condiciones.ServicioClausulaWCF.IServicioClausulas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServicioClausulasClient : System.ServiceModel.ClientBase<Condiciones.ServicioClausulaWCF.IServicioClausulas>, Condiciones.ServicioClausulaWCF.IServicioClausulas {
        
        public ServicioClausulasClient() {
        }
        
        public ServicioClausulasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClausulasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClausulasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClausulasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Condiciones.ServicioClausulaWCF.GruposClausulaDTO ObtenerCondiciones(Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO Consulta, string Usuario, string Clave) {
            return base.Channel.ObtenerCondiciones(Consulta, Usuario, Clave);
        }
        
        public string ObtenerCondicionesXml(string XmlConsulta, string Usuario, string Clave) {
            return base.Channel.ObtenerCondicionesXml(XmlConsulta, Usuario, Clave);
        }
        
        public string ConvertirConsulta(Condiciones.ServicioClausulaWCF.ConsultaCondicionesDTO Consulta) {
            return base.Channel.ConvertirConsulta(Consulta);
        }
        
        public string ConvertirGrupos(Condiciones.ServicioClausulaWCF.GruposClausulaDTO Grupos) {
            return base.Channel.ConvertirGrupos(Grupos);
        }
    }
}
