//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condiciones.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Desarrollo_F4/Condiciones/CondicionesParser/")]
        public string Ubicacion {
            get {
                return ((string)(this["Ubicacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://serviciocondiciones.assist-card.com/ServicioClausulasWS.asmx")]
        public string Condiciones_com_assist_card_serviciocondiciones_ServicioClausulasWS {
            get {
                return ((string)(this["Condiciones_com_assist_card_serviciocondiciones_ServicioClausulasWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://benefitsws.pre.assist-card.com/ServicioClausulasWS.asmx")]
        public string Condiciones_ClausulasWSPreProd_ServicioClausulasWS {
            get {
                return ((string)(this["Condiciones_ClausulasWSPreProd_ServicioClausulasWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4736/ServicioClausulasWS.asmx")]
        public string Condiciones_ClausulasWSLocalHost_ServicioClausulasWS {
            get {
                return ((string)(this["Condiciones_ClausulasWSLocalHost_ServicioClausulasWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://benefitsws.dev.assist-card.com/ServicioClausulasWS.asmx")]
        public string Condiciones_ClausulasWSTest_ServicioClausulasWS {
            get {
                return ((string)(this["Condiciones_ClausulasWSTest_ServicioClausulasWS"]));
            }
        }
    }
}
