//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondicionesMigracion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.0.111\\ANDROMEDA;Initial Catalog=Condiciones;User ID=sa;Passwor" +
            "d=kingkong;\" providerName=\"System.Data.SqlClient")]
        public string CnxStrCondiciones {
            get {
                return ((string)(this["CnxStrCondiciones"]));
            }
            set {
                this["CnxStrCondiciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.0.111\\ANDROMEDA;Initial Catalog=Portal;User ID=sa;Password=kin" +
            "gkong;\" providerName=\"System.Data.SqlClient")]
        public string CnxStrPortal {
            get {
                return ((string)(this["CnxStrPortal"]));
            }
            set {
                this["CnxStrPortal"] = value;
            }
        }
    }
}
