BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Tarifa ADD
	IdTipoModalidad int NOT NULL CONSTRAINT DF_Tarifa_IdTipoModalidad DEFAULT 1
GO
ALTER TABLE dbo.Tarifa SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
